services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  CodeTool\OpenSearch\Index\IndexConfigFactory:
    class: CodeTool\OpenSearch\Index\IndexConfigFactory
    arguments:
      - '%opensearch.config.indexes%'
  CodeTool\OpenSearch\Index\IndexManager:
    arguments:
      - '@CodeTool\OpenSearch\Index\IndexConfigFactory'
      - '@OpenSearch\Client'
  CodeTool\OpenSearch\Command\IndexActionCommand:
    arguments:
      $indexManager: '@OpenSearchBundle\Service\IndexManager'
