services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  CodeTool\OpenSearch\Field\BuiltinFieldFactory:
    class: CodeTool\OpenSearch\Field\BuiltinFieldFactory
    tags:
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\BooleanField::FIELD_TYPE_BOOLEAN }
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\DateField::FIELD_TYPE_DATE}
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\FloatField::FIELD_TYPE_FLOAT }
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\GeoPointField::FIELD_TYPE_GEO_POINT }
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\GeoShapeField::FIELD_TYPE_GEO_SHAPE }
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\IntegerField::FIELD_TYPE_INTEGER }
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\KeywordField::FIELD_TYPE_KEYWORD }
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\ObjectField::FIELD_TYPE_OBJECT }
      - { name: opensearch.field.factory, type: !php/const CodeTool\OpenSearch\Field\TextField::FIELD_TYPE_TEXT }
  CodeTool\OpenSearch\Field\FieldFactoryRegistry:
    class: CodeTool\OpenSearch\Field\FieldFactoryRegistry
  CodeTool\OpenSearch\Field\FieldFactoryInterface: '@CodeTool\OpenSearch\Field\FieldFactoryRegistry'
  CodeTool\OpenSearch\Index\Manager:
    class: CodeTool\OpenSearch\Index\Manager
  CodeTool\OpenSearch\Command\CreateCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\Manager'
  CodeTool\OpenSearch\Command\DeleteCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\Manager'
  CodeTool\OpenSearch\Command\ListCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\Manager'
  CodeTool\OpenSearch\Command\PopulateCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\Manager'
