services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  CodeTool\OpenSearch\Index\IndexManager:
    arguments:
      - '@OpenSearch\Client'
  CodeTool\OpenSearch\Command\IndexCreateCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\IndexManager'
  CodeTool\OpenSearch\Command\IndexDeleteCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\IndexManager'
  CodeTool\OpenSearch\Command\IndexListCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\IndexManager'
  CodeTool\OpenSearch\Command\IndexPopulateCommand:
    arguments:
      $indexManager: '@CodeTool\OpenSearch\Index\IndexManager'
